package com.epsilon.training.programs;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;

import com.epsilon.training.util.DbUtil;
import com.epsilon.training.util.KeyboardUtil;

public class GetAutogeneratedPrimaryKey {

	public static void main(String[] args) {
		System.out.println("Enter new product details: ");
		String name = KeyboardUtil.getString("Name           : ");
		String brand = KeyboardUtil.getString("Brand          : ");
		String category = KeyboardUtil.getString("Category       : ");
		String quantityPerUnit = KeyboardUtil.getString("QPU            : ");
		String description = KeyboardUtil.getString("Description    : ");
		String picture = KeyboardUtil.getString("Picture        : ");
		double unitPrice = KeyboardUtil.getDouble("Unit price     : ");
		int discount = KeyboardUtil.getInt("Discount       : ");
		
		String sql = "insert into products values(null, ?, ?, ?, ?, ?, ?, ?, ?)";
		
		try (Connection conn = DbUtil.createConnection(); 
			PreparedStatement stmt = conn.prepareStatement(sql, Statement.RETURN_GENERATED_KEYS);
		) {
			
			stmt.setString(1, category);
			stmt.setString(2, name);
			stmt.setString(3, brand);
			stmt.setString(4, description);
			stmt.setString(5, quantityPerUnit);
			stmt.setDouble(6, unitPrice);
			stmt.setString(7, picture);
			stmt.setInt(8, discount);
			
			stmt.execute(); // brings the auto-generated primary key values
			
			// access the generated primary key values from a result set
			ResultSet keys = stmt.getGeneratedKeys();
			if(keys.next()) {
				int id = keys.getInt(1); // there is only one column with one row (for the current scenario)
				System.out.println("Product data added with primary key " + id);
			}
			
		} catch (Exception ex) {
			ex.printStackTrace();
		}
	}

}
